[build]
target = "wasm32-unknown-unknown"

[target.'cfg(target_arch = "wasm32")']
rustflags = ["-C", "target-feature=+simd128,+atomics,+bulk-memory,+mutable-globals"]

[unstable]
build-std = ["panic_abort", "std"]